INSERT INTO MAP_OBJECT_TYPE (OBJECT_TYPE_ID, GROUP_ID, MODEL3D, NAME, ROTATION, TEXTURE, TYPE, VERSION) VALUES
(0, 0, '/../../../src/assets/3D_Models/Streets/straight_road.gltf', 'Gerade', 0, '/img/streetplaner/object-icons/Road_straight.svg', 'STREET', 0),
(1, 0, '/../../../src/assets/3D_Models/Streets/curved_road.gltf', 'Kurve', 0, '/img/streetplaner/object-icons/Road_curve.svg', 'STREET', 0),
(2, 0, '/../../../src/assets/3D_Models/Streets/intersection_road.gltf', 'Kreuzung', 0, '/img/streetplaner/object-icons/Road_cross.svg', 'STREET', 0),
(3, 1, '/../../../src/assets/3D_Models/Building/house_high.gltf', 'Großes Gebäude', 0, '/img/streetplaner/buildings/BigBuilding.png', 'BUILDING', 0),
(4, 1, '/../../../src/assets/3D_Models/Building/house.gltf', 'Gebäude', 0, '/img/streetplaner/buildings/Building.png', 'BUILDING', 0),
(5, 1, '/../../../src/assets/3D_Models/Building/shop.gltf', 'Supermarkt', 0, '/img/streetplaner/buildings/Supermarkt.png', 'BUILDING', 0),
(6, 1, '/../../../src/assets/3D_Models/Building/stadium.gltf', 'Stadion', 0, '/img/streetplaner/buildings/Stadium.png', 'BUILDING', 0),
(7, 3, '/../../../src/assets/3D_Models/Pedestrians/firefighter.gltf', 'Feuerwehrmann', 0, '/img/streetplaner/pedestrian/Firefighter.png', 'PEDESTRIAN', 0),
(8, 3, '/../../../src/assets/3D_Models/Pedestrians/pedestrianBlondeBlack.gltf', 'Fussgänger', 0, '/img/streetplaner/pedestrian/pedestrianBlondeBlack.png', 'PEDESTRIAN', 0),
(9, 3, '/../../../src/assets/3D_Models/Pedestrians/pedestrianBlondeBlue.gltf', 'Fussgänger', 0, '/img/streetplaner/pedestrian/pedestrianBlondeBlue.png', 'PEDESTRIAN', 0),
(10, 3, '/../../../src/assets/3D_Models/Pedestrians/pedestrianBrowneBlue.gltf', 'Fussgänger', 0, '/img/streetplaner/pedestrian/pedestrianBrowneBlue.png', 'PEDESTRIAN', 0),
(11, 3, '/../../../src/assets/3D_Models/Pedestrians/pedestrianBrowneRed.gltf', 'Fussgänger', 0, '/img/streetplaner/pedestrian/pedestrianBrowneRed.png', 'PEDESTRIAN', 0),
(12, 3, '/../../../src/assets/3D_Models/Pedestrians/pedestrianBrownePink.gltf', 'Fussgänger', 0, '/img/streetplaner/pedestrian/pedestrianBrowneRed.png', 'PEDESTRIAN', 0),
(13, 3, '/../../../src/assets/3D_Models/Pedestrians/pedestrianOrangeGreen.gltf', 'Fussgänger', 0, '/img/streetplaner/pedestrian/pedestrianOrangeGreen.png', 'PEDESTRIAN', 0),
(14, 3, '/../../../src/assets/3D_Models/Pedestrians/pedestrianOrangeWhite.gltf', 'Fussgänger', 0, '/img/streetplaner/pedestrian/pedestrianOrangeWhite.png', 'PEDESTRIAN', 0),
(15, 3, '/../../../src/assets/3D_Models/Pedestrians/pedestrianRed.gltf', 'Fussgänger', 0, '/img/streetplaner/pedestrian/pedestrianRed.png', 'PEDESTRIAN', 0),
(16, 3, '/../../../src/assets/3D_Models/Pedestrians/PoliceOfficer.gltf', 'Fussgänger', 0, '/img/streetplaner/pedestrian/PoliceOfficer.png', 'PEDESTRIAN', 0);