INSERT INTO MAP_OBJECT_TYPE (OBJECT_TYPE_ID, GROUP_ID, MODEL3D, NAME, ROTATION, TEXTURE, TYPE, VERSION)
VALUES (0, 0, '/../../../src/assets/3D_Models/Streets/straight_road.gltf', 'Gerade', 0,
        '/img/streetplaner/object-icons/gerade.png', 'STREET', 0),
       (1, 0, '/../../../src/assets/3D_Models/Streets/curved_road.gltf', 'Kurve', 0,
        '/img/streetplaner/object-icons/kurve.png', 'STREET', 0),
       (2, 0, '/../../../src/assets/3D_Models/Streets/intersection_road.gltf', 'Kreuzung', 0,
        '/img/streetplaner/object-icons/kreuzung.png', 'STREET', 0),
       (3, 1, '/../../../src/assets/3D_Models/Building/house_high.gltf', 'Großes Gebäude', 0,
        '/img/streetplaner/building/BigBuilding.png', 'BUILDING', 0),
       (4, 1, '/../../../src/assets/3D_Models/Building/house.gltf', 'Gebäude', 0,
        '/img/streetplaner/building/Building.png', 'BUILDING', 0),
       (5, 1, '/../../../src/assets/3D_Models/Building/shop.gltf', 'Supermarkt', 0,
        '/img/streetplaner/building/Supermarkt.png', 'BUILDING', 0),
       (7, 2, '', 'Auto', 0, '/img/streetplaner/object-icons/car-top-view.svg', 'ASSET', 0),
       (8, 0, '/../../../src/assets/3D_Models/Streets/streetCrossing.gltf', 'Fußgängerüberweg', 0,
        '/img/streetplaner/object-icons/crosswalk.png', 'RAIL', 0),
       (9, 0, '/../../../src/assets/3D_Models/Railroad/straight_rail.gltf', 'Schiene Gerade', 0,
        '/img/streetplaner/object-icons/gerade_schiene.png', 'RAIL', 0),
       (10, 0, '/../../../src/assets/3D_Models/Railroad/curved_rail.gltf', 'Schiene Kurve', 0,
        '/img/streetplaner/object-icons/curve_schiene.png', 'RAIL', 0),
       (11, 0, '/../../../src/assets/3D_Models/Railroad/trainstation.gltf', 'Bahnhof', 0,
        '/img/streetplaner/object-icons/trainstation.png', 'RAIL', 0),
       (12, 0, '/../../../src/assets/3D_Models/Railroad/road_train_crossing.gltf', 'Bahnübergang', 0,
        '/img/streetplaner/object-icons/road_train_crossing.png', 'RAIL', 0),
       (13, 2, '', 'Startpunkt', 0, '/img/streetplaner/object-icons/car-top-view-red.svg', 'ASSET', 0),
       (14, 3, '', 'Zug', 0, '/img/streetplaner/object-icons/thomas_symbol.png', 'ASSET', 0),

       (15, 1, '/../../../src/assets/3D_Models/Building/skyscraper1.gltf', 'Wolkenkratzer1', 0,
        '/img/streetplaner/building/skyscraper1.png', 'BUILDING', 0),
       (16, 1, '/../../../src/assets/3D_Models/Building/skyscraper2.gltf', 'Wolkenkratzer2', 0,
        '/img/streetplaner/building/skyscraper2.png', 'BUILDING', 0),
       (17, 1, '/../../../src/assets/3D_Models/Building/skyscraper3.gltf', 'Wolkenkratzer3', 0,
        '/img/streetplaner/building/skyscraper3.png', 'BUILDING', 0),
       (18, 1, '/../../../src/assets/3D_Models/Building/citybuilding1.gltf', 'Haus1', 0,
        '/img/streetplaner/building/citybuilding1.png', 'BUILDING', 0),
       (19, 1, '/../../../src/assets/3D_Models/Building/citybuilding2.gltf', 'Haus2', 0,
        '/img/streetplaner/building/citybuilding2.png', 'BUILDING', 0),
       (20, 1, '/../../../src/assets/3D_Models/Building/citybuilding3.gltf', 'Haus3', 0,
        '/img/streetplaner/building/citybuilding3.png', 'BUILDING', 0),

       (50, 4, '/../../../src/assets/3D_Models/Pedestrians/pedestrianBlondeBlack.gltf', 'Fussgänger', 0,
        '/img/streetplaner/object-icons/pedestrian-top-view.png', 'ASSET', 0),
       (51, 4, '/../../../src/assets/3D_Models/Pedestrians/pedestrianBlondeBlue.gltf', 'Fussgänger', 0,
        '/img/streetplaner/object-icons/pedestrian-top-view.png', 'ASSET', 0),
       (52, 4, '/../../../src/assets/3D_Models/Pedestrians/pedestrianBrowneBlue.gltf', 'Fussgänger', 0,
        '/img/streetplaner/object-icons/pedestrian-top-view.png', 'ASSET', 0),
       (53, 4, '/../../../src/assets/3D_Models/Pedestrians/pedestrianBrowneRed.gltf', 'Fussgänger', 0,
        '/img/streetplaner/object-icons/pedestrian-top-view.png', 'ASSET', 0),
       (54, 4, '/../../../src/assets/3D_Models/Pedestrians/pedestrianBrownPink.gltf', 'Fussgänger', 0,
        '/img/streetplaner/object-icons/pedestrian-top-view.png', 'ASSET', 0),
       (55, 4, '/../../../src/assets/3D_Models/Pedestrians/pedestrianOrangeGreen.gltf', 'Fussgänger', 0,
        '/img/streetplaner/object-icons/pedestrian-top-view.png', 'ASSET', 0),
       (56, 4, '/../../../src/assets/3D_Models/Pedestrians/pedestrianOrangeWhite.gltf', 'Fussgänger', 0,
        '/img/streetplaner/object-icons/pedestrian-top-view.png', 'ASSET', 0),
       (57, 4, '/../../../src/assets/3D_Models/Pedestrians/pedestrianRed.gltf', 'Fussgänger', 0,
        '/img/streetplaner/object-icons/pedestrian-top-view.png', 'ASSET', 0),
       (58, 4, '/../../../src/assets/3D_Models/Pedestrians/PoliceOfficer.gltf', 'Polizist', 0,
        '/img/streetplaner/object-icons/pedestrian-top-view.png', 'ASSET', 0),
       (59, 4, '/../../../src/assets/3D_Models/Pedestrians/Firefighter.gltf', 'Feuerwehrmann', 0,
        '/img/streetplaner/object-icons/pedestrian-top-view.png', 'ASSET', 0);
